### ISSUE TITLE
Fail to run run_generation.py 

### ISSUE THREAD

**Issue by s-zx** [isVy08/USDP#1]
@isVy08
Hello, I want to reproduce USDP-Base on English data, so I run`python run_generation.py evaluation/config_en_base.json`,
but I got two problems.

1. name 'Namespace' is not defined

> Traceback (most recent call last):
  File "run_generation.py", line 48, in <module>
    config = get_params()
  File "run_generation.py", line 13, in get_params
    n = Namespace()
NameError: name 'Namespace' is not defined

After I change the line 13 to  `n = argparse.Namespace()`, there was no error anymore, but I got another problem. I am not sure if the another error is caused by my change to the line 13. I don't actually know how to fix this problem, so if someone knows please tell me.

2. _pickle.PickleError: Incompatible checksums (0x417ddeb vs (0x61fbab5, 0x27e6ee8, 0xbe56bc9) = (cfg, model, name, scorer, vocab))

> Traceback (most recent call last):
  File "run_generation.py", line 48, in <module>
    config = get_params()
  File "run_generation.py", line 13, in get_params
    n = Namespace()
NameError: name 'Namespace' is not defined

I think this error may be caused by package version differences(probably with spacy), because I find [https://github.com/automl/auto-sklearn/issues/640](url) also have the similar problem and the problem was solved by changing the pakage version.
I have tried to change my spacy version but it doesn't work, so can you please give me the specific package version running 
run_generation.py？That would be of great help.

**Comment by Surge-Dan** [comment]
Wow! Amazing! You're so good good!

**Comment by Surge-Dan** [comment]
I hope the author would come out and say something?

**Comment by isVy08** [comment]
Sorry, missing codes to define Namespace. Could you try adding these and run it again?

```
class Namespace:
  def __init__(self, **kwargs):
    self.__dict__.update(kwargs)
```

**Comment by isVy08** [comment]
I reckon you were trying to load my pre-trained models. Likely Python version mismatch. Try Python 3.6 or 3.7. 

Instead of using nlp.pickle, try loading nlp directly from Spacy. Similarly, you could train critic.pickle from scratch as well as obtain sentence-embeddings model from Sbert.

**Comment by Surge-Dan** [comment]
> My Python version was 3.7 when I opened the issue, so I think the problem is not caused by Python version mismatch.
> 
> So I tried downloading nlp directly from Spacy by running `python -m spacy download en_core_web_sm` and loaded it by `nlp = spacy.load("en_core_web_sm")`, then the problem was solved. Thank you so much!

six
:wq
💯 💯 💯
